# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/Testproject.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  project: '**/Testproject.csproj'
  IISWebsiteName: 'AzureTestProject'
  

stages:
  - stage: DeployWebsite
    displayName: 'Deploy website'
    pool:
      vmImage: windows-latest
    
    jobs:
    - deployment: DeployWebsite
      displayName: 'Deploy website'
      environment: 'MySystem.TEO-AHTESHAM1'
      strategy:
       runOnce:
           deploy:
            steps:
                - task: NuGetToolInstaller@1
                  name: 'NuGetToolInstaller'
                  displayName: 'NuGet tool installer'

                - task: NuGetCommand@2
                  name: 'NuGetRestore'
                  displayName: 'NuGet restore packages'
                  inputs:
                    command: 'restore'
                    restoreSolution: '$(solution)'
                    feedsToUse: 'select'

                - task: DotNetCoreCLI@2
                  name: 'Tests'
                  displayName: 'Run tests'
                  inputs:
                    command: 'test'
                    projects: '$(solution)'
                    arguments: '--configuration $(BuildConfiguration)'

                - task: PublishBuildArtifacts@1
                  inputs:
                    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                    ArtifactName: 'drop'
                    publishLocation: 'Container'

                - task: IISWebAppDeploymentOnMachineGroup@0
                  name: 'DeployIIS'
                  displayName: 'Deploy IIS website'                
                  inputs:
                    WebSiteName: '${{ variables.IISWebsiteName }}'
                    Package: '$(Pipeline.Workspace)\buildPipeline\drop\TestProject'
                    TakeAppOfflineFlag: true
